# Generated by Django 3.1.2 on 2020-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_image/%Y/%m/%d/', verbose_name='Изображение категории'),
        ),
    ]
